[package]
name = "unzip"
description = "Library to decompress all (or some) files from a zipped archive."
version = "1.0.1"
authors = ["SonnyX <randy@vonderweide.nl>" , "Ryan Leonard (http://ryanleonard.us)"]
license = "MIT"

[dev-dependencies]
temporary = "0.7"

[dependencies]
zip = "6.0"
